name: Haskell CI with Nix Flake

on:
  workflow_dispatch:
  pull_request:
    branches: [main, unstable]
  push:
    branches: [main, unstable]
  schedule:
    - cron: '0 0 * * 0' # Weekly to maintain cache

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout code

    - name: Setup Nix with Flakes support
      uses: cachix/install-nix-action@v14
      with:
        install_url: https://nixos-nix-install-tests.cachix.org/serve/3g0jw47z2ms7gwm2q5q3b4j2b2vrpq5j/install
        extra_nix_config: |
          experimental-features = nix-command flakes

    - name: Build with Nix Flake
      run: |
        nix build .#pelotero-engine:exe:generators --show-trace

    - name: Run Executable
      run: ./result/bin/generators

    # Optional: Cache Nix store to speed up builds
    - uses: actions/cache@v2
      with:
        path: /nix/store
        key: ${{ runner.os }}-nix-${{ hashFiles('flake.lock') }}
        restore-keys: |
          ${{ runner.os }}-nix-
